/*
 * 公共表情
 */
(function(window) {
    var expression = {
        emoji:{
            data:[
                {title: '1', src: '../../expression/emoji/1.gif'},
                {title: '2', src: '../../expression/emoji/2.gif'},
                {title: '3', src: '../../expression/emoji/3.gif'},
                {title: '4', src: '../../expression/emoji/4.gif'},
                {title: '5', src: '../../expression/emoji/5.gif'},
                {title: '6', src: '../../expression/emoji/6.gif'},
                {title: '7', src: '../../expression/emoji/7.gif'},
                {title: '8', src: '../../expression/emoji/8.gif'},
                {title: '9', src: '../../expression/emoji/9.gif'},
                {title: '10', src: '../../expression/emoji/10.gif'},
                {title: '11', src: '../../expression/emoji/11.gif'},
                {title: '12', src: '../../expression/emoji/12.gif'},
                {title: '13', src: '../../expression/emoji/13.gif'},
                {title: '14', src: '../../expression/emoji/14.gif'},
                {title: '15', src: '../../expression/emoji/15.gif'},
                {title: '16', src: '../../expression/emoji/16.gif'},
                {title: '17', src: '../../expression/emoji/17.gif'},
                {title: '18', src: '../../expression/emoji/18.gif'},
                {title: '19', src: '../../expression/emoji/19.gif'},
                {title: '20', src: '../../expression/emoji/20.gif'},
                {title: '21', src: '../../expression/emoji/21.gif'},
                {title: '22', src: '../../expression/emoji/22.gif'},
                {title: '23', src: '../../expression/emoji/23.gif'},
                {title: '24', src: '../../expression/emoji/24.gif'},
                {title: '25', src: '../../expression/emoji/25.gif'},
                {title: '26', src: '../../expression/emoji/26.gif'},
                {title: '27', src: '../../expression/emoji/27.gif'},
                {title: '28', src: '../../expression/emoji/28.gif'},
                {title: '29', src: '../../expression/emoji/29.gif'},
                {title: '30', src: '../../expression/emoji/30.gif'},
                {title: '31', src: '../../expression/emoji/31.gif'},
                {title: '32', src: '../../expression/emoji/32.gif'},
                {title: '33', src: '../../expression/emoji/33.gif'},
                {title: '34', src: '../../expression/emoji/34.gif'},
                {title: '35', src: '../../expression/emoji/35.gif'},
                {title: '36', src: '../../expression/emoji/36.gif'},
                {title: '37', src: '../../expression/emoji/37.gif'},
                {title: '38', src: '../../expression/emoji/38.gif'},
                {title: '39', src: '../../expression/emoji/39.gif'},
                {title: '40', src: '../../expression/emoji/40.gif'},
                {title: '41', src: '../../expression/emoji/41.gif'},
                {title: '42', src: '../../expression/emoji/42.gif'},
                {title: '43', src: '../../expression/emoji/43.gif'},
                {title: '44', src: '../../expression/emoji/44.gif'},
                {title: '45', src: '../../expression/emoji/45.gif'},
                {title: '46', src: '../../expression/emoji/46.gif'},
                {title: '47', src: '../../expression/emoji/47.gif'},
                {title: '48', src: '../../expression/emoji/48.gif'},
                {title: '49', src: '../../expression/emoji/49.gif'},
                {title: '50', src: '../../expression/emoji/50.gif'},
                {title: '51', src: '../../expression/emoji/51.gif'},
                {title: '52', src: '../../expression/emoji/52.gif'},
                {title: '53', src: '../../expression/emoji/53.gif'},
                {title: '54', src: '../../expression/emoji/54.gif'},
                {title: '55', src: '../../expression/emoji/55.gif'},
                {title: '56', src: '../../expression/emoji/56.gif'},
                {title: '57', src: '../../expression/emoji/57.gif'},
                {title: '58', src: '../../expression/emoji/58.gif'},
                {title: '59', src: '../../expression/emoji/59.gif'},
                {title: '60', src: '../../expression/emoji/60.gif'},
                {title: '61', src: '../../expression/emoji/61.gif'},
                {title: '62', src: '../../expression/emoji/62.gif'},
                {title: '63', src: '../../expression/emoji/63.gif'},
                {title: '64', src: '../../expression/emoji/64.gif'},
                {title: '65', src: '../../expression/emoji/65.gif'},
                {title: '66', src: '../../expression/emoji/66.gif'},
                {title: '67', src: '../../expression/emoji/67.gif'},
                {title: '68', src: '../../expression/emoji/68.gif'},
                {title: '69', src: '../../expression/emoji/69.gif'},
                {title: '70', src: '../../expression/emoji/70.gif'},
                {title: '71', src: '../../expression/emoji/71.gif'},
                {title: '72', src: '../../expression/emoji/72.gif'},
                {title: '73', src: '../../expression/emoji/73.gif'},
                {title: '74', src: '../../expression/emoji/74.gif'},
                {title: '75', src: '../../expression/emoji/75.gif'},
                {title: '76', src: '../../expression/emoji/76.gif'},
                {title: '77', src: '../../expression/emoji/77.gif'},
                {title: '78', src: '../../expression/emoji/78.gif'},
                {title: '79', src: '../../expression/emoji/79.gif'},
                {title: '80', src: '../../expression/emoji/80.gif'},
                {title: '81', src: '../../expression/emoji/81.gif'},
                {title: '82', src: '../../expression/emoji/82.gif'},
                {title: '83', src: '../../expression/emoji/83.gif'},
                {title: '84', src: '../../expression/emoji/84.gif'},
                {title: '85', src: '../../expression/emoji/85.gif'},
                {title: '86', src: '../../expression/emoji/86.gif'},
                {title: '87', src: '../../expression/emoji/87.gif'},
                {title: '88', src: '../../expression/emoji/88.gif'},
                {title: '89', src: '../../expression/emoji/89.gif'},
                {title: '90', src: '../../expression/emoji/90.gif'},
                {title: '91', src: '../../expression/emoji/91.gif'}
            ]
        },
        tieba:{
            data:[
                {title: '1', src: '../../expression/tieba/1.jpg'},
                {title: '2', src: '../../expression/tieba/2.jpg'},
                {title: '3', src: '../../expression/tieba/3.jpg'},
                {title: '4', src: '../../expression/tieba/4.jpg'},
                {title: '5', src: '../../expression/tieba/5.jpg'},
                {title: '6', src: '../../expression/tieba/6.jpg'},
                {title: '7', src: '../../expression/tieba/7.jpg'},
                {title: '8', src: '../../expression/tieba/8.jpg'},
                {title: '9', src: '../../expression/tieba/9.jpg'},
                {title: '10', src: '../../expression/tieba/10.jpg'},
                {title: '11', src: '../../expression/tieba/11.jpg'},
                {title: '12', src: '../../expression/tieba/12.jpg'},
                {title: '13', src: '../../expression/tieba/13.jpg'},
                {title: '14', src: '../../expression/tieba/14.jpg'},
                {title: '15', src: '../../expression/tieba/15.jpg'},
                {title: '16', src: '../../expression/tieba/16.jpg'},
                {title: '17', src: '../../expression/tieba/17.jpg'},
                {title: '18', src: '../../expression/tieba/18.jpg'},
                {title: '19', src: '../../expression/tieba/19.jpg'},
                {title: '20', src: '../../expression/tieba/20.jpg'},
                {title: '21', src: '../../expression/tieba/21.jpg'},
                {title: '22', src: '../../expression/tieba/22.jpg'},
                {title: '23', src: '../../expression/tieba/23.jpg'},
                {title: '24', src: '../../expression/tieba/24.jpg'},
                {title: '25', src: '../../expression/tieba/25.jpg'},
                {title: '26', src: '../../expression/tieba/26.jpg'},
                {title: '27', src: '../../expression/tieba/27.jpg'},
                {title: '28', src: '../../expression/tieba/28.jpg'},
                {title: '29', src: '../../expression/tieba/29.jpg'},
                {title: '30', src: '../../expression/tieba/30.jpg'},
                {title: '31', src: '../../expression/tieba/31.jpg'},
                {title: '32', src: '../../expression/tieba/32.jpg'},
                {title: '33', src: '../../expression/tieba/33.jpg'},
                {title: '34', src: '../../expression/tieba/34.jpg'},
                {title: '35', src: '../../expression/tieba/35.jpg'},
                {title: '36', src: '../../expression/tieba/36.jpg'},
                {title: '37', src: '../../expression/tieba/37.jpg'},
                {title: '38', src: '../../expression/tieba/38.jpg'},
                {title: '39', src: '../../expression/tieba/39.jpg'},
                {title: '40', src: '../../expression/tieba/40.jpg'},
                {title: '41', src: '../../expression/tieba/41.jpg'},
                {title: '42', src: '../../expression/tieba/42.jpg'},
                {title: '43', src: '../../expression/tieba/43.jpg'},
                {title: '44', src: '../../expression/tieba/44.jpg'},
                {title: '45', src: '../../expression/tieba/45.jpg'},
                {title: '46', src: '../../expression/tieba/46.jpg'},
                {title: '47', src: '../../expression/tieba/47.jpg'},
                {title: '48', src: '../../expression/tieba/48.jpg'},
                {title: '49', src: '../../expression/tieba/49.jpg'},
                {title: '50', src: '../../expression/tieba/50.jpg'}
            ]
        },
    }
    window.Expression = expression;

})(window);
