var zh = {
    "chat": "聊天",
    "mail_list": "通讯录",
    "my_friend": "我的好友",
    "my_group": "我的群组",
    "new_friend": "新的好友",
    "quotation": "行情",
    "flash_exchange": "闪兑",
    "not_yet_open": "暂未开放",
    "payment_code": "收款码",
    "authentication": "实名认证",
    "autograph": "签名",
    "no_autograph": "您还未填写签名",
    "account_backup_tips": "提示：请尽快备份助记词，否则账户丢失将无法找回",
    "backup_wallet": "备份钱包",
    "view_notice": "查看公告",
    "wallet": "钱包",
    "find": "发现",
    "mine": "我的",
    "logon_expired": "登录已过期，请重新登录",
    "connecting": "连接中...",
    "certified": "已认证",
    "in_certification": "认证中",
    "uncertified": "未认证",
    "accept": "接受",
    "accepted": "已接受",
    "adopted": "已通过",
    "agree_join_group": "同意入群",
    "agreed_join_group": "已同意入群",
    "tips": "提示",
    "confirm_delete": "您确定要删除吗？",
    "you_get_a_redpaper": "您领取一个红包",
    "get_a_redpaper": "领取了红包",
    "copy": "复制",
    "send_to_friend": "发送给朋友",
    "delete": "删除",
    "recall": "撤回",
    "congratulations": "恭喜发财，大吉大利",
    "not_support_video": "您的浏览器不支持 audio 元素",
    "confirm_recall": "您确定要撤回吗?",
    "see_redpaper": "查看红包",
    "get_redpaper": "领取红包",
    "see_redpaper_get_yet": "查看红包(已领取)",
    "received": "已领取",
    "expired": "已过期",
    "token_over": "已被领完",
    "has_been_received": "已被领取",
    "hold_to_talk": "按住说话",
    "release_end": "松开结束",
    "send": "发送",
    "album": "相册",
    "shot": "拍摄",
    "red_packet": "红包",
    "voice_too_short": "您发送的语音太短",
    "you_get_a_redpacket_from": "您领取了对方一个红包",
    "other_side_get_your_redpacket": "对方领取了您的红包",
    "message_send_but_rejected": "信息已发出，但被对方拒收了",
    "duration": "时长",
    "group_chat_name": "群聊名称",
    "please_fill_in_group_chat_name": "请填写群聊名称",
    "group_brief": "群聊简介",
    "please_fill_in_group_brief": "请填写群聊简介",
    "allow_recommend_group": "允许推荐该群",
    "group_can_be_searched_recommended": "开启后，群可被搜到以及被推荐",
    "create": "创建",
    "create_group_chat": "创建群聊",
    "reset": "重置",
    "cancel": "取消",
    "set_group_brief": "设置群简介",
    "finish": "完成",
    "group_member": "群成员",
    "group_qrcode": "群二维码",
    "group_notice": "群公告",
    "group_verification": "群验证",
    "group_confirm_invite": "启用后，群成员需群主确认后才能邀请朋友进群。",
    "message_free": "消息免打扰",
    "place_group_to_top": "设为置顶群聊",
    "send_message": "发消息",
    "exit_group_chat": "退出群聊",
    "ungroup": "解散群组",
    "set_yet": "已设置",
    "set_not": "未设置",
    "only_admin_can_set_grief": "只有管理员才能设置群简介",
    "only_admin_can_set_notice": "只有管理员才能设置群公告",
    "confirm_exit_group": "您确定要退出群组吗？",
    "confirm_ungroup": "您确定要解散群组吗？",
    "group_message": "群信息",
    "group_number": "群号",
    "please_choose_contact": "请选择联系人",
    "choose_contact": "选择联系人",
    "new_members": "新增成员",
    "you_did_not_select_contact": "您未选择联系人",
    "search_nothing": "搜索不到您想要的！",
    "please_select_member": "请选择成员",
    "remove_member": "移除成员",
    "search": "搜索",
    "search_id_mobile": "搜索ID或手机号",
    "please_enter_username": "请输入用户名",
    "change_group_name": "修改群名称",
    "please_fill_in_group_notice": "请填写群公告",
    "set_group_notice": "设置群公告",
    "join_now": "立即加入",
    "scan_qrcode_add_group": "扫描二维码加入群聊",
    "share_to_friend": "分享给好友",
    "scan": "扫一扫",
    "you_need_apply_into_group": "你需要申请入群",
    "please_enter": "请输入",
    "apply_to_info": "申请加入",
    "group_application_sent_successfully": "入群申请发送成功",
    "add_group_verification": "加群验证",
    "sorry_no_one_you_look_for": "抱歉，没有你要找的人",
    "oneself": "本人",
    "already_your_friend": "已是您好友",
    "add_friend": "添加好友",
    "you_need_seed_verify": "你需要发送验证申请等待对方通过",
    "add_to_address_book": "添加到通讯录",
    "nothing": "无",
    "sended_wait_for_pass": "已发送申请验证，等待对方通过",
    "friend_verification": "好友验证",
    "please_enter_search_content": "请输入搜索内容",
    "do_not_set_permissions": "不设置权限",
    "donot_let_him_see_circle": "不让他看我的朋友圈",
    "donot_look_his_circle": "不看他的朋友圈",
    "set_success": "设置成功",
    "nickname": "昵称",
    "friend_circle": "朋友圈",
    "set_friend_circle_permissions": "设置朋友圈权限",
    "friends_card": "好友名片",
    "remark": "备注",
    "common_group": "共同群组",
    "join_blacklist": "加入黑名单",
    "accept_and_add_friend": "接受并添加到通讯录",
    "already_add_to_book": "已添加到通讯录",
    "confirm_delete_friend": "您确定要删除该好友吗？",
    "delete_success": "删除成功",
    "personal_qrcode": "个人二维码",
    "delete_friend": "删除好友",
    "personal_info": "个人信息",
    "scan_and_add_friend": "扫一扫添加好友",
    "scan_hintText": "对准条形码/二维码，即可自动扫描",
    "scan_albumText": "相册",
    "scan_lightText": "轻触照亮",
    "scan_closeText": "轻触关闭",
    "friend_note": "好友备注",
    "please_set_friend_note": "请设置好友备注",
    "set_friend_note": "设置好友备注",
    "save": "保存",
    "pic_address_invalid": "图片地址无效，无法保存",
    "save_success": "保存成功",
    "save_fail": "保存失败，请重试",
    "confirm_send_to_group": "您确定要发送给群",
    "confirm_send_to_friend": "您确定要发送给好友",
    "send_succcess": "发送成功",
    "public_everyone_can_see": "公开——众人皆可见",
    "only_myself_can_see": "仅自己可见",
    "change_background": "更换背景",
    "prise": "赞",
    "comment": "评论",
    "please_enter_a_comment": "请输入评论内容",
    "year": "年",
    "month": "月",
    "day1": "日",
    "delete_info": "删除信息",
    "operation_success": "操作成功",
    "total": "共",
    "piece": "张",
    "today": "今天",
    "save_to_album": "保存到相册",
    "send_friendship_circle": "发朋友圈",
    "choose_picture": "选择图片",
    "image_library": "图片库",
    "camera": "相机",
    "modify_successfully": "修改成功",
    "moment_thought": "这一刻的想法...",
    "who_can_see": "谁可以看",
    "public": "公开",
    "please_fill_in_moment_thought": "请填写这一刻的想法...",
    "published_successfully": "发表成功",
    "no_more_than_nine_pic": "图片不能超过9张",
    "publish": "发表",
    "nothing_to_search": "对不起，没有找到您想要的",
    "application": "应用",
    "information": "资讯",
    "media": "媒体",
    "function_development": "功能开发中",
    "game": "游戏",
    "no_more": "没有数据了",
    "detail": "详情",
    "group_received_a_picture": "群里收到一张图片",
    "group_received_a_voice": "群里收到一段语音",
    "group_received_a_redpacket": "群里收到一个红包",
    "group_some_people_get_a_redpacket": "群里有人领取红包",
    "you_send_a_picture": "您给对方发了一张图片",
    "you_receive_a_picture": "您收到一张图片",
    "you_send_a_voice": "您给对方发了一段语音",
    "you_receive_a_voice": "您收到一段语音",
    "you_send_a_redpacket": "您给对方发了一个红包",
    "you_receive_a_redpacket": "您收到一个红包",
    "you_get_a_redpacket": "您领取了对方的红包",
    "you_give_a_redpacket": "对方领取了您的红包",
    "scan_own_qrcode": "请扫描本平台二维码",
    "group": "群组",
    "friend": "好友",
    "search_friend_or_group": "搜索好友/群",
    "group_people_limit": "群人数上限",
    "people": "人",
    "save_image": "保存图片",

    "easy_game": "娱乐游戏",
    "apply": "应用",
    "retract": "收起",
    "more": "更多",
    "link_invalid": "链接地址无效",
    "immediately": "立即",
    "partake": "参与",
    "see": "查看",
    "profit": "收益",
    "all_record": "全部记录",
    "in_revenue": "收益中",
    "completed": "已完成",
    "participation_time": "参与时间",
    "participation_amount": "参与金额",
    "participation_status": "参与状态",
    "immediate_participation": "立即参与",
    "game_rule": "游戏规则",
    "pool_of_funds": "资金池",
    "please_enter_the_number_of_participants": "请输入参与数量",
    "consume": "消耗",
    "balance": "余额",
    "miner_fee": "矿工费",
    "please_enter_wallet_password": "请输入钱包密码",
    "my_profit": "我的收益",
    "can_receive": "可领取",
    "income_received": "领取收益",
    "team_award": "团队奖励",
    "no_profit": "无收益",
    "no_team_reward": "无团队奖励",
    "please_enter_deal_password": "请输入支付密码",
    "participation_income": "参与收益",
    "team_profit": "团队收益",
    "collection_records": "领取记录",
    "trading_block_number": "交易区块号",
    "extracted_amount": "提取金额",
    "income_collection": "收益领取",
    "arrival_record": "到账记录",
    "income_time": "收益时间",
    "day": "天",
    "hour": "时",
    "minute": "分",
    "second": "秒",
    "participation_record": "参与记录",
    "profit_record": "收益记录",
    "total_assets": "总资产",
    "please_backup": "请备份",
    "asset_transfer": "资产划转",
    "currency_trading": "币币交易",
    "asset": "资产",
    "please_scan_payment_code": "请扫描收款码",
    "my_wallet": "我的钱包",
    "create_wallet": "创建钱包",
    "import_wallet": "导入钱包",
    "recent_transaction_record": "最近交易记录",
    "packing": "打包中",
    "transfer_accounts": "转账",
    "receivables": "收款",
    "create_wallet_tips1": "密码用于保护保护私钥和交易授权，强度非常重要",
    "create_wallet_tips2": "我们不存储密码，也无法帮您找回，请务必记牢",
    "wallet_name": "钱包名称",
    "password": "密码",
    "repeat_password": "重复密码",
    "confirm_and_agree": "确认及代表同意",
    "agreement": "协议",
    "confirm": "确认",
    "please_enter_wallet_name": "请输入钱包名称",
    "please_enter_wallet_password": "请输入钱包密码",
    "please_repeat_wallet_password": "请重复钱包密码",
    "repeat_password_is_deff": "重复密码与密码不一致",
    "please_confirm_and_agree": "请确认及同意",
    "create_wallet_success": "钱包创建成功",
    "mobile": "手机号",
    "please_enter_mobile_number": "请输入手机号码",
    "verification_code": "验证码",
    "please_enter_verification_code": "请输入验证码",
    "new_password": "新密码",
    "password_format": "8-12位字母或者数字组合",
    "confirm_password": "确认密码",
    "get_verify_code": "获取验证码",
    "please_enter_new_password": "请输入新密码",
    "please_enter": "请输入",
    "please_confirm_login_password": "请确认登录密码",
    "confirm_password_is_diff": "确认密码与登录密码不一致",
    "please_enter_password": "请输入密码",
    "password_reset_success": "密码重置成功",
    "return": "返回",
    "mnemonic_reset_password": "助记词重置密码",
    "enter_account_mnemonic_tips": "请输入账户助记词(用英文逗号,隔开)",
    "please_enter_mnemonic": "请输入助记词",
    "please_enter_login_password": "请输入登录密码",
    "please_enter_image_verify": "请输入图形验证码",
    "sign_in": "登录",
    "register_new_user": "注册新用户",
    "retrieve_password": "找回密码",
    "sign_in_success": "登录成功",
    "not_create_wallet_tips": "您还没有创建钱包，请先创建",
    "nickname": "昵称",
    "please_enter_nickname": "请输入昵称",
    "login_password": "登录密码",
    "payment_password": "支付密码",
    "payment_password_format": "6位纯数字",
    "invite_code": "邀请码",
    "please_enter_invite_code": "请输入邀请码(选填)",
    "register": "注册",
    "please_scan_share_code": "请扫描分享码!",
    "please_enter_number_password": "请输入6位纯数字支付密码",
    "register_success": "注册成功",
    "use_protocol": "使用协议",
    "privacy_clause": "隐私条款",
    "about": "关于我们",
    "edit_avatar": "编辑头像",
    "current_password": "当前密码",
    "please_enter_current_password": "请输入当前密码",
    "please_enter_repeat_password": "请输入重复密码",
    "password_edited_login_again": "您的密码已修改，请重新登录",
    "change_login_password": "修改登录密码",
    "please_confirm_password": "请确认密码",
    "confirm_newpassword_is_diff": "确认密码与新密码不一致",
    "set_deal_password": "设置支付密码",
    "transaction_number": "交易号",
    "time": "时间",
    "transaction_record": "交易记录",
    "all": "全部",
    "type": "类型",
    "please_choose_type": "请选择类型",
    "choose_time": "选择时间",
    "title": "标题",
    "content": "内容",
    "costomer_service_reply": "客服回复",
    "feedback_detail": "反馈详情",
    "please_describe_your_problem": "请描述您的问题",
    "submit": "提交",
    "please_enter_title": "请输入标题",
    "feedback_record": "反馈记录",
    "problem_feedback": "问题反馈",
    "record": "记录",
    "currency_choice": "币种选择",
    "game_balance": "游戏余额",
    "proportion": "比例",
    "reversal_quantity": "转回数量",
    "please_enter_reversal_quantity": "请输入转回数量",
    "one": "1",
    "game_currency": "游戏币",
    "recharge_quantity": "充值数量",
    "please_enter_recharge_quantity": "请输入充值数量",
    "game_recharge": "游戏充值",
    "recharge": "充值",
    "reversal": "转回",
    "recharge_record": "充值记录",
    "reversal_record": "转回记录",
    "upload_avatar_tips": "上传头像小伙伴更好识别哦",
    "please_set_your_nickname": "请输入您的昵称",
    "introduce_yourself": "简单介绍下自己(50个字)",
    "personal_info_settings": "个人信息设置",
    "manage_wallet": "管理钱包",
    "invite_friend": "邀请好友",
    "my_invitation": "我的邀请",
    "my_team": "我的团队",
    "contact_customer_service": "联系客服",
    "language_switching": "语言切换",
    "version_info": "版本信息",
    "serial_number": "序号",
    "user_id": "用户ID",
    "mobile_number": "手机号码",
    "notice_detail": "公告详情",
    "latest_release_date": "最新发布时间",
    "notice": "公告",
    "scan_screenshots": "截图扫一扫",
    "set_sign": "设置个性签名",
    "please_enter_sign": "请输入个性签名",
    "modify_avatar": "修改头像",
    "signature": "个性签名",
    "logout": "退出",
    "confirm_logout": "您确定要退出登录吗？",
    "set_nickname": "设置昵称",
    "please_set_nickname": "请设置昵称",
    "settings": "设置",
    "quantity": "量",
    "ten_thousand": "万",
    "store_small_change": "已存入零钱，可用来发红包",
    "red_envelope_amount": "红包金额",
    "wait_receive": "等待对方领取",
    "one_red_envelope": "一个红包共",
    "red_envelopes": "红包",
    "received_red_envelopes": "收到红包",
    "bese_of_luck": "手气最佳",
    "red_pack_received": "收到的红包",
    "close": "关闭",
    "send_out": "发送",
    "available_balance": "可用余额",
    "amount": "数量",
    "please_enter_amount": "请输入数量",
    "stuff_red_packet": "塞入红包",
    "no_available_balance": "您没有可用余额",
    "msg_sended": "短信已发送,请注意查收",
    "msg_send_fail": "短信发送失败",
    "please_enter_right_amount": "请输入正确的数量",
    "insufficient_balance": "您当前余额不足",
    "total_send_redpacket": "发出红包总数",
    "send_red_envelop": "发出的红包",
    "give_red_envelop": "发红包",
    "receive": "领取",
    "currently_for": "当前为",
    "lucky_red_envelop": "拼手气红包",
    "normal_red_evelop": "普通红包",
    "change_normal_red_envelope": "改为普通红包",
    "change_lucky_red_evelope": "改为拼手气红包",
    "please_fill_in_number": "请填写个数",
    "see_receipt_detail": "查看领取详情",
    "give_you_a_redpacket": "给您发了个红包",
    "open": "开",
    "received_altogether": "一共收到",
    "send_out_red_envelopes": "发出去红包",
    "buying_price": "买入价格",
    "buying_quantity": "买入数量",
    "turnover": "交易额",
    "buy_in": "买入",
    "can_buy": "可买",
    "usable": "可用",
    "freeze": "冻结",
    "sell": "卖",
    "buy": "买",
    "unit_price": "单价",
    "please_enter_buy_price": "请输入买入价格",
    "please_enter_buy_amount": "请输入买入数量",
    "buy_amount_not_enough": "可买数量不足",
    "sell_out": "卖出",
    "cancel_order_yet": "已撤单",
    "cancel_order": "撤单",
    "commission_price": "委托价",
    "surplus_quantity": "剩余数量",
    "confirm_cancell": "您确定要撤销吗？",
    "transaction_volume": "成交数量",
    "transaction_price": "成交价格",
    "transaction_turnover": "成交额",
    "selling_price": "卖出价格",
    "selling_quantity": "卖出数量",
    "can_sell": "可卖",
    "please_enter_sell_price": "请输入卖出价格",
    "please_enter_sell_amount": "请输入卖出数量",
    "sell_amount_not_enough": "可卖数量不足",
    "current_delegation": "当前委托",
    "historical_delegate": "历史委托",
    "receive_wallet_address": "收款人钱包地址",
    "transfer_amount": "转账金额",
    "current_balance": "当前余额",
    "slow": "慢",
    "fast": "快",
    "please_enter_receive_wallet_address": "请输入收款人钱包地址",
    "please_enter_transfer_amount": "请输入转账金额",
    "from": "来自",
    "to": "发到",
    "account": "账户",
    "please_enter_transform_amount": "请输入划转金额",
    "all_transfer": "全部划转",
    "remark_choise": "备注(选填)",
    "roll_out": "转出",
    "shift_to": "转入",
    "pay_party": "发款方",
    "receive_party": "收款方",
    "block": "区块",
    "no_copy_content": "没有可复制内容",
    "transform_record": "划转记录",
    "transfer_to_wallet": "转出到钱包",
    "transfer_to_currency_account": "转入到币币账户",
    "wallet_backup_tips1": "抄写下你的账户助记词",
    "wallet_backup_tips2": "备份账户：导出“助记词”并抄写到安全的地方，千万不要保存到网络上。",
    "wallet_backup_tips3": "请确认您的账户助记词",
    "wallet_backup_tips4": "请按照顺序点击助记词，以确保您的备份助记词正确",
    "wallet_backup_tips5": "如果有人获取了你的助记词将直接获取你的资产！请抄写下助记词并存放在安全的地方",
    "next": "下一步",
    "confirm_reset": "您确定重置吗？",
    "please_backup_words": "请备份完整助记词",
    "backup_account": "备份账户",
    "no_screenshots.": "请勿截图",
    "got_it": "知道了",
    "change_password": "修改密码",
    "forget_or_import": "忘记密码？导入助记词或私钥可重置密码",
    "delete_wallet": "删除钱包",
    "please_enter_receive_amount": "请输入收款金额",
    "plaintext_private_key": "明文私钥",
    "start_importing": "开始导入",
    "please_enter_key": "请输入Key",
    "import_keystore_tips": "复制粘贴以太坊官方钱包 Keystore 文件内容至输入框或通过扫描 Keystore 内容生成的二维码录入。",
    "keystore_text_content": "Keystore文本内容",
    "keystore_password": "Keystore密码",
    "please_enter_keystore": "请输入keystore",
    "mnemonic_word": "助记词",
    "private_key": "私钥",
    "word_only_in_lucky": "助记词仅在lucky中使用",
    "export": "导出",
    "price": "价格",
    "Chg": "涨跌幅",
    "message": "消息",
    "logon_has_expired": "登录已过期，请重新登录",
    "connection": "连接中",
    "network_is_error": "网络开了小差，请稍后重试",
    "drop_down_refresh": "下拉刷新",
    "release_and_refresh": "松开刷新",
    "drop_down_loading": "下拉加载",
    "release_and_loading": "松开加载",
    "loading": "加载中",
    "copy_success": "复制成功",
    'copy_fail': "复制失败，请重试",
    "just": "刚刚",
    "minutes_ago": "分钟前",
    "today": "今天",
    "yesterday": "昨天",
    "return_exit": "再按一次返回键退出",
    "Sunday": "周日",
    "Monday": "周一",
    "Tuesday": "周二",
    "Wednesday": "周三",
    "Thursday": "周四",
    "Friday": "周五",
    "Saturday": "周六",
    "before_dawn": "凌晨",
    "morning": "早上",
    "afternoon": "下午",
    "night": "晚上",
    "noon": "中午",
    "before_yesterday": "前天",
    "hintText": "对准条形码/二维码，即可自动扫描",
    "albumText": "相册",
    "lightText": "轻触照亮",
    "closeText": "轻触关闭",
    "Number": "个数",
    "this_group": "本群共",
    "copy_address": "复制地址",
    "share_friend":"分享好友",
    "push_setting": "消息推送设置",
    "set_success": "设置成功",

    "withdraw_coin": "提币",
    "withdraw_coin_address": "提币地址",
    "withdraw_coin_amoiunt": "提币数量",
    "please_enter_withdraw_coin_address": "请输入提币地址",
    "please_enter_withdraw_coin_amount": "请输入提币数量",
    "please_enter_remark": "请输入备注",

    "apply_game_agent": "申请游戏推广",
    "your_is_agent": "您已经是代理",
    "submit_apply": "提交申请",




    "wechat_sign_in": "微信登录",
    "phone_register": "手机号注册",
    "tip_nickname": "昵称仅用于展示不能用户登录",
    "forget_password": "忘记密码",
    "bind_phone": "绑定手机号",
    "safe": "安全",
    "notice": "通知",
    "complaint": "举报投诉",
    "bank_card": "银行卡",
    "authentication_failed": "认证失败",
    "my": "我的",
    "Please_keep_the_verification_code_carefully": "验证码请勿提供给他人，请谨慎保存",
    "Please_confirm_payment_password": "请确认支付密码",
    "reasons_for_reporting": "举报原因",
    "Please_enter_the_content": "请输入内容",
    "reply_time": "回复时间",
    "ID_number": "身份证号",
    "Please_enter_ID_number": "请输入身份证号",
    "Upload_ID_card_front_picture": "上传身份证正面图片",
    "Upload_ID_card_back_picture": "上传身份证背面图片",
    "Please_enter_your_name": "请输入姓名",
    "name": "姓名",
    "upload_audit": "上传审核",
    "system_message": "系统消息",
    "user_message": "用户消息",
    "recharge_message": "充值消息",
    "withdraw_message": "提现消息",
    "push_notification_settings": "推送通知设置",
    "set_up_successfully": "设置成功",
    "logout_account": "退出账号",
    "share": "分享",
    "Are_you_sure_to_delete_this_session": "您确定要删除该会话吗？",
    "game_redpacket": "游戏红包",
    "go_to_talk_with_your_friends": "快去找好友聊天吧～",
    "network_connection": "网络连接中...",
    "message_notification": "消息通知",
    "group_chat": "群聊",
    "blacklist": "黑名单",
    "initiate_group_chat": "发起群聊",
    "tip_scan": "请扫描本平台个人或群聊二维码",
    "remove_from_blacklist": "移出黑名单",
    "Are_you_sure_to_remove_from_the_blacklist": "您确定要移出黑名单吗",
    "Do_you_want_to_open_an_external_link": "您是否要打开外部链接？",
    "group_validity_period": "群有效期",
    "tip_open_group": "开启后，群永久有效",
    "select_expiration_date": "选择有效期",
    "group_brief": "群简介",
    "members_add_friends_to_each_other": "群成员互加好友",
    "total_ban": "全体禁言",
    "Only_the_group_leader_can_modify_the_Avatar": "只有群主才能修改头像",
    "add": "添加",
    "search_mobile": "搜索手机号",
    "head": "头像",
    "sex": "性别",
    "male": "男",
    "female": "女",
    "birthday": "生日",
    "my_QR": "我的二维码",
    "set_sex": "设置性别",
    "personal_settings": "个人设置",
    "Amount": "金额",
    "yuan": "元",
    "ge": "个",

    'mine_extract_coin': '提币',
    'wallet_choose_coin': '选择币种',
    'account_balance': '账户余额',
    "wallet_get_coin_num": "提币数量",
    'wallet_service_charge': '手续费',
    'wallet_coin_address': '提币地址',
    'network_error': '服务器开了小差，请重新尝试',
    'msg_enter_coin_number': '请输入提币数量',
    'msg_enter_coin_address': '请输入提币地址',
    'regex_pay_password': '请输入6位纯数字支付密码',
    'msg_submit_success_audite': '提交成功,审核中',
    'home_receipt': '收款',
    'home_coin': '币种',
    'wallet_receipt_address': '收款地址',
    'wallet_receipt_money': '收款金额',
    'wallet_receipt_money_please': '请输入金额',
    'transfer': '转帐',
    'wallet_receipt_address_please': '收款人钱包地址',
    'wallet_transfer_money': '转账金额',
    'wallet_cur_balance': '当前余额',
    'msg_receipt_wallet_address': '请输入收款人钱包地址',
    'msg_enter_transfer_money': '请输入转账金额',
    'confirm_enter_wallet_password': '请输入钱包支付密码',
    'please_enter_pay_password': '请输入支付密码',
    'order_number': '订单编号',
    'coin_type': '币种',
    'coin_number': '数量',
    "wallet_record": '钱包记录',
    "withdraw": '提币',
    "transfer": '转账',
    "copy_wallet_address": '复制钱包地址',
    "video": '视频',
    "upload_successfully": '上传成功',
    'group_received_a_video': '群里收到一个视频',
    'you_send_a_video': '您给对方发了一个视频',
    'you_receive_a_video': '您收到一个视频',
    "name_card": '名片',
    "single_card": '个人名片',
    "group_card": '群名片',
    "send_card": '发送名片',
    'group_received_a_card': '群里收到一个名片',
    'you_send_a_card': '您给对方发了一个名片',
    'you_receive_a_card': '您收到一个名片',
    "file": '文件',
    "send_successfully": '发送成功',
    "tip_file_limit": '文件大小不能超过25MB！',
    'group_received_a_file': '群里收到一个文件',
    'you_send_a_file': '您给对方发了一个文件',
    'you_receive_a_file': '您收到一个文件',
    "recharge_success": '充值成功',
    "recharge_failed": '充值失败',
    "withdraw_success": '提币成功',
    "withdrawing": '提币中',
    "withdraw_failed": '提币驳回',
    "address": '地址',
    "withdraw_record": '提币记录',

    "mall": '商城',
}

var cht = {

}

var en = {
  "chat": "Chats",
  "mail_list": "Contacts",
  "my_friend": "My Friends",
  "my_group": "My Groups",
  "new_friend": "New friend",
  "quotation": "Quotation",
  "flash_exchange": "Flash exchange",
  "not_yet_open": "Not yet open",
  "payment_code": "Payment code",
  "authentication": "KYC Authentication",
  "autograph": "Signature",
  "no_autograph": "You haven't signature yet.",
  "account_backup_tips": "Tips: Please back up the mnemonic now, otherwise the lost account will not be recovered.",
  "backup_wallet": "Backup Wallet",
  "view_notice": "More",
  "wallet": "Wallet",
  "find": "Discover",
  "mine": "Me",
  "logon_expired": "Login Session Expired. Please re-login again.",
  "connecting": "Connecting",
  "certified": "Certified",
  "in_certification": "Pending",
  "uncertified": "None",
  "accept": "Accept",
  "accepted": "Accepted",
  "adopted": "Added",
  "agree_join_group": "Join",
  "agreed_join_group": "Joined Group",
  "tips": "Tips",
  "confirm_delete": "Are you sure to delete it?",
  "you_get_a_redpaper": "You get a red packet",
  "get_a_redpaper": "Received the red packet",
  "copy": "Copy",
  "send_to_friend": "Send to Chat",
  "delete": "Delete",
  "recall": "Recall",
  "congratulations": "Good Day",
  "not_support_video": "Your browser does not support audio elements",
  "confirm_recall": "Are you sure to recall?",
  "see_redpaper": "Check the red packet",
  "get_redpaper": "Receive a red packet",
  "see_redpaper_get_yet": "Check the red packet (Received)",
  "received": "Received",
  "expired": "Expired",
  "token_over": "Have been completed",
  "has_been_received": "Accepted",
  "hold_to_talk": "Hold To Talk",
  "release_end": "Release To Send",
  "send": "Send",
  "album": "Album",
  "shot": "Camera",
  "red_packet": "Red Packet",
  "voice_too_short": "Your voice is too short",
  "you_get_a_redpacket_from": "Red Packet Received.",
  "other_side_get_your_redpacket": "Your Friend accepted Red Packet.",
  "message_send_but_rejected": "The message was sent but rejected by the other party.",
  "duration": "Duration",
  "group_chat_name": "Group Chat Name",
  "please_fill_in_group_chat_name": "Please fill in the name of group chat.",
  "group_brief": "Description of group chat",
  "please_fill_in_group_brief": "Please fill in the group chat Brief",
  "allow_recommend_group": "Allow recommendation of this group",
  "group_can_be_searched_recommended": "After opening, the group can be searched and recommended.",
  "create": "Create",
  "create_group_chat": "Creating group chat",
  "reset": "Reset",
  "cancel": "Cancel",
  "set_group_brief": "Introduction to Setup Groups",
  "finish": "Finish",
  "group_member": "Group members",
  "group_qrcode": "Group QRcode",
  "group_notice": "Group notice",
  "group_verification": "Group validation",
  "group_confirm_invite": "When enabled, group members need confirmation from the group owner before inviting friends to join the group.",
  "message_free": "No interruption of news",
  "place_group_to_top": "Set it as top group chat",
  "send_message": "Send message",
  "exit_group_chat": "Quit group chat",
  "ungroup": "Disbanded group",
  "set_yet": "Set up",
  "set_not": "Not set up",
  "only_admin_can_set_grief": "Only Administrators Can Set up Group Profiles",
  "only_admin_can_set_notice": "Only administrators can set up group announcements",
  "confirm_exit_group": "Are you sure you want to quit the group?",
  "confirm_ungroup": "Are you sure you want to disband the group?",
  "group_message": "Group information",
  "group_number": "Group number",
  "please_choose_contact": "Please select a contact person",
  "choose_contact": "Choose contacts",
  "new_members": "New member",
  "you_did_not_select_contact": "You did not select a contact",
  "search_nothing": "You can't find what you want!",
  "please_select_member": "Please select members",
  "remove_member": "Remove Members",
  "search": "Search",
  "search_id_mobile": "Search for ID or cell phone number",
  "please_enter_username": "Enter one user name",
  "change_group_name": "Modify the group name",
  "please_fill_in_group_notice": "Please fill in the group announcement",
  "set_group_notice": "Setting up group announcements",
  "join_now": "Immediate accession",
  "scan_qrcode_add_group": "Scanning QRcode code to join group chat",
  "share_to_friend": "Share it with friends",
  "scan": "Scan",
  "you_need_apply_into_group": "You need to apply for membership",
  "please_enter": "Please input",
  "apply_to_info": "Application for accession",
  "group_application_sent_successfully": "Successful application for group membership",
  "add_group_verification": "Additive group validation",
  "sorry_no_one_you_look_for": "Sorry, there's no one you're looking for.",
  "oneself": "Oneself",
  "already_your_friend": "Already your good friend",
  "add_friend": "Add friends",
  "you_need_seed_verify": "You need to send a validation application for approval.",
  "add_to_address_book": "Add to Address Book",
  "nothing": "Nothing",
  "sended_wait_for_pass": "Application has been sent for verification, waiting for the other party to pass",
  "friend_verification": "Friend verification",
  "please_enter_search_content": "Please enter the search content",
  "do_not_set_permissions": "Do not set permissions",
  "donot_let_him_see_circle": "Don't let him see my circle of friends",
  "donot_look_his_circle": "Don't look at his circle of friends",
  "set_success": "Set up successfully",
  "nickname": "Nickname",
  "friend_circle": "Circle of friends",
  "set_friend_circle_permissions": "Setting Friendship Circle Rights",
  "friends_card": "Friend card",
  "remark": "Remarks",
  "common_group": "Common group",
  "join_blacklist": "Blacklist",
  "accept_and_add_friend": "Accept and add to address book",
  "already_add_to_book": "Added to Address Book",
  "confirm_delete_friend": "Are you sure you want to delete this friend?",
  "delete_success": "Delete successful",
  "personal_qrcode": "Personal QRcode",
  "delete_friend": "Delete friends",
  "personal_info": "Personal information",
  "scan_and_add_friend": "Sweep and add friends",
  "scan_hintText": "Alignment bar code/two-dimensional code, automatic scanning",
  "scan_albumText": "Album",
  "scan_lightText": "Touch and light up",
  "scan_closeText": "Touch close",
  "friend_note": "Friend notes",
  "please_set_friend_note": "Please set friends'notes",
  "set_friend_note": "Setting Friends'Notes",
  "save": "Save",
  "pic_address_invalid": "The picture address is invalid and cannot be saved",
  "save_success": "Save successfully",
  "save_fail": "Save failed, please try again",
  "confirm_send_to_group": "You are sure you want to send it to the group",
  "confirm_send_to_friend": "You are sure you want to send it to your friends",
  "send_succcess": "Send successfully",
  "public_everyone_can_see": "Openness - visible to all",
  "only_myself_can_see": "Seen only by oneself",
  "change_background": "Change background",
  "prise": "Fabulous",
  "comment": "Comment",
  "please_enter_a_comment": "Please enter comments",
  "year": "year",
  "month": "month",
  "day": "day",
  "delete_info": "Delete information",
  "operation_success": "Successful operation",
  "total": "Total",
  "piece": "piece",
  "today": "today",
  "save_to_album": "Save to album",
  "send_friendship_circle": "Circle of friends",
  "choose_picture": "Select pictures",
  "image_library": "Picture library",
  "camera": "camera",
  "modify_successfully": "Modified success",
  "moment_thought": "Thoughts at this moment...",
  "who_can_see": "Who can see it?",
  "public": "Open",
  "please_fill_in_moment_thought": "Please fill in your thoughts at this moment....",
  "published_successfully": "Publish success",
  "no_more_than_nine_pic": "No more than nine pictures",
  "publish": "Publish",
  "nothing_to_search": "Sorry, I didn't find what you wanted.",
  "application": "Apply",
  "information": "Information",
  "media": "Media",
  "function_development": "Functional development",
  "game": "Game",
  "no_more": "No more data.",
  "detail": "Details",
  "group_received_a_picture": "A picture was received in the group.",
  "group_received_a_voice": "A voice was heard in the group.",
  "group_received_a_redpacket": "A red envelope was received in the group.",
  "group_some_people_get_a_redpacket": "Someone in the group received red envelopes.",
  "you_send_a_picture": "You sent a picture to each other.",
  "you_receive_a_picture": "You received a picture.",
  "you_send_a_voice": "You sent a voice to each other.",
  "you_receive_a_voice": "You receive a voice",
  "you_send_a_redpacket": "You sent a red envelope to the other party",
  "you_receive_a_redpacket": "You received a red envelope",
  "you_get_a_redpacket": "You get your partner's red envelope",
  "you_give_a_redpacket": "The other party received your red envelope.",
  "scan_own_qrcode": "Please scan the QRcode of this platform.",
  "group": "Group",
  "friend": "Good friend",
  "search_friend_or_group": "Search for Friends/Groups",
  "group_people_limit": "Upper limit of group size",
  "people": "people",
  "save_image": "Save pictures",

  "easy_game": "Games",
  "apply": "Apply",
  "retract": "Retract",
  "more": "More",
  "link_invalid": "Invalid Link Address",
  "immediately": "immediately",
  "partake": "participate in",
  "see": "See",
  "profit": "Profit",
  "all_record": "All records",
  "in_revenue": "In revenue",
  "completed": "Completed",
  "participation_time": "Participation time",
  "participation_amount": "Participation amount",
  "participation_status": "Participation status",
  "immediate_participation": "Immediate participation",
  "game_rule": "Rules of the game",
  "pool_of_funds": "Pool of funds",
  "please_enter_the_number_of_participants": "Please enter the number of participants",
  "consume": "consume",
  "balance": "Balance",
  "miner_fee": "Miner's fee",
  "please_enter_wallet_password": "Please enter your wallet password",
  "my_profit": "My income",
  "can_receive": "Available for collection",
  "income_received": "Income received",
  "team_award": "Team award",
  "no_profit": "No gain",
  "no_team_reward": "No team reward",
  "please_enter_deal_password": "Please enter the transaction password",
  "participation_income": "Participation income",
  "team_profit": "Team profit",
  "collection_records": "Collection records",
  "trading_block_number": "Trading Block Number",
  "extracted_amount": "Sum of money extracted",
  "income_collection": "Income collection",
  "arrival_record": "Arrival record",
  "income_time": "Yield time",
  "day1": "day",
  "hour": "hour",
  "minute": "minute",
  "second": "second",
  "participation_record": "Attendance record",
  "profit_record": "Income record",
  "total_assets": "total assets",
  "please_backup": "Backup",
  "asset_transfer": "Asset transfer",
  "currency_trading": "Currency trading",
  "asset": "Assets",
  "please_scan_payment_code": "Please scan the receipt code",
  "my_wallet": "My wallet",
  "create_wallet": "Create Wallet",
  "import_wallet": "Import Wallet",
  "recent_transaction_record": "Recent Transaction Records",
  "packing": "Packing",
  "transfer_accounts": "Transfer accounts",
  "receivables": "Receivables",
  "create_wallet_tips1": "Passwords are used to protect private keys and transaction authorization. Strength is very important.",
  "create_wallet_tips2": "We don't store passwords and we can't find them for you. Please keep them in mind.",
  "wallet_name": "Wallet name",
  "password": "Password",
  "repeat_password": "Repeat password",
  "confirm_and_agree": "Confirmation and Representative's Consent",
  "agreement": "agreement",
  "confirm": "Confirm",
  "please_enter_wallet_name": "Please enter the name of your wallet.",
  "please_enter_wallet_password": "Please enter your wallet password",
  "please_repeat_wallet_password": "Please repeat your wallet password",
  "repeat_password_is_deff": "Duplicate password is inconsistent with password",
  "please_confirm_and_agree": "Please confirm and agree",
  "create_wallet_success": "Wallet Creation Success",
  "mobile": "Phone number",
  "please_enter_mobile_number": "Please enter your cell phone number.",
  "verification_code": "Verification Code",
  "please_enter_verification_code": "Please enter the verification code.",
  "new_password": "New password",
  "password_format": "8-12-bit combination of letters or numbers",
  "confirm_password": "Confirm password",
  "get_verify_code": "Get code",
  "please_enter_new_password": "Please enter a new password",
  "please_enter": "Please input",
  "please_confirm_login_password": "Please confirm the login password",
  "confirm_password_is_diff": "Confirmation password is inconsistent with login password",
  "please_enter_password": "Please input a password",
  "password_reset_success": "Password Reset Successfully",
  "return": "Return",
  "mnemonic_reset_password": "Mnemonic reset password",
  "enter_account_mnemonic_tips": "Please enter an account mnemonic (separated by commas in English)",
  "please_enter_mnemonic": "Please enter mnemonics",
  "please_enter_login_password": "Please enter your login password",
  "please_enter_image_verify": "Please enter the Graphic Verification Code",
  "sign_in": "Sign in",
  "register_new_user": "Register new users",
  "retrieve_password": "Retrieve password",
  "sign_in_success": "Login successfully",
  "not_create_wallet_tips": "You haven't created your wallet yet. Please create it first.",
  "please_enter_nickname": "Please enter a nickname",
  "login_password": "Login password",
  "payment_password": "Transaction password",
  "payment_password_format": "6-bit pure number",
  "invite_code": "Invitation code",
  "please_enter_invite_code": "Please enter the invitation code (optional)",
  "register": "Register",
  "please_scan_share_code": "Please scan the Sharing Code!",
  "please_enter_number_password": "Please enter a 6-bit pure digital trading password",
  "register_success": "Regiseter success",
  "use_protocol": "Use protocol",
  "privacy_clause": "Privacy clause",
  "about": "About",
  "edit_avatar": "Editor's head",
  "current_password": "Current password",
  "please_enter_current_password": "Please enter the current password",
  "please_enter_repeat_password": "Please enter a duplicate password",
  "password_edited_login_again": "Your password has been changed. Please log in again.",
  "change_login_password": "Modify login password",
  "please_confirm_password": "Please confirm your password.",
  "confirm_newpassword_is_diff": "Confirm that the password is inconsistent with the new password",
  "set_deal_password": "Set transaction password",
  "transaction_number": "Transaction number",
  "time": "time",
  "transaction_record": "Transaction record",
  "all": "all",
  "type": "type",
  "please_choose_type": "Please select the type",
  "choose_time": "Selection time",
  "title": "Title",
  "content": "Content",
  "costomer_service_reply": "Customer service reply",
  "feedback_detail": "Feedback details",
  "please_describe_your_problem": "Please describe your problem.",
  "submit": "Submit",
  "please_enter_title": "Please enter the title",
  "feedback_record": "Feedback record",
  "problem_feedback": "Feedback",
  "record": "record",
  "currency_choice": "Currency choice",
  "game_balance": "Game balance",
  "proportion": "Proportion",
  "reversal_quantity": "Reversal quantity",
  "please_enter_reversal_quantity": "Please enter the number of rollbacks",
  "one": "One",
  "game_currency": "Game currency",
  "recharge_quantity": "Recharge quantity",
  "please_enter_recharge_quantity": "Please enter the recharge quantity",
  "game_recharge": "Game recharge",
  "recharge": "Recharge",
  "reversal": "Turn back",
  "recharge_record": "Recharge record",
  "reversal_record": "Reversal record",
  "upload_avatar_tips": "Upload avatars for better identification",
  "please_set_your_nickname": "Enter nickname",
  "introduce_yourself": "Introduce yourself briefly (50 words)",
  "personal_info_settings": "Personal Information Settings",
  "manage_wallet": "Management Wallet",
  "invite_friend": "Invite friends",
  "my_invitation": "My invitation",
  "my_team": "My team",
  "contact_customer_service": "Contact customer service",
  "language_switching": "Language switching",
  "version_info": "Version",
  "serial_number": "Serial number",
  "user_id": "User ID",
  "mobile_number": "Phone number",
  "notice_detail": "Announcement details",
  "latest_release_date": "Latest release date",
  "notice": "Notice",
  "scan_screenshots": "Scan screenshots",
  "set_sign": "Setting Personal Signature",
  "please_enter_sign": "Please enter your signature",
  "modify_avatar": "Modifying head",
  "signature": "Personalized signature",
  "logout": "Sign out",
  "confirm_logout": "Are you sure you want to log out?",
  "set_nickname": "Set Nickname",
  "please_set_nickname": "Please set a nickname",
  "settings": "Settings",
  "quantity": "quantity",
  "ten_thousand": "ten thousand",
  "store_small_change": "Change has been deposited and can be used to distribute red envelopes",
  "red_envelope_amount": "Amount of red envelope",
  "wait_receive": "Waiting for the other party to collect",
  "one_red_envelope": "A red envelope",
  "red_envelopes": "Red envelopes",
  "received_red_envelopes": "Receive a red envelope",
  "bese_of_luck": "Best of luck",
  "red_pack_received": "Red Pack Received",
  "close": "Close",
  "send_out": "Send",
  "available_balance": "Available balance",
  "amount": "Quantity",
  "please_enter_amount": "Please enter quantity",
  "stuff_red_packet": "Stuffed in red packets",
  "no_available_balance": "You have no available balance",
  "msg_sended": "Short message has been sent, please check it carefully.",
  "msg_send_fail": "Failed to send SMS",
  "please_enter_right_amount": "Please enter the correct number",
  "insufficient_balance": "Your current balance is insufficient",
  "total_send_redpacket": "Total number of red envelopes issued",
  "send_red_envelop": "Red envelope",
  "give_red_envelop": "Hand out red envelopes",
  "receive": "Receive",
  "currently_for": "Currently for",
  "lucky_red_envelop": "A red envelope",
  "normal_red_evelop": "Ordinary red envelope",
  "change_normal_red_envelope": "Change to ordinary red envelope",
  "change_lucky_red_evelope": "Change it to a hand-to-hand red envelope",
  "please_fill_in_number": "Please fill in the number",
  "see_receipt_detail": "See Receipt Details",
  "give_you_a_redpacket": "A red envelope was sent to you.",
  "open": "open",
  "received_altogether": "Received altogether",
  "send_out_red_envelopes": "Send out red envelopes",
  "buying_price": "Buying price",
  "buying_quantity": "Buying quantity",
  "turnover": "Turnover",
  "buy_in": "Buy",
  "can_buy": "Can buy",
  "usable": "Usable",
  "freeze": "Frozen",
  "sell": "Sell",
  "buy": "Buy",
  "unit_price": "unit price",
  "please_enter_buy_price": "Please enter the purchase price.",
  "please_enter_buy_amount": "Please enter the purchase quantity",
  "buy_amount_not_enough": "Shortage of available quantity",
  "sell_out": "Sell out",
  "cancel_order_yet": "Withdrawal of documents",
  "cancel_order": "Cancel the order",
  "commission_price": "Commission price",
  "surplus_quantity": "Surplus quantity",
  "confirm_cancell": "Are you sure you want to revoke it?",
  "transaction_volume": "Transaction volume",
  "transaction_price": "Transaction price",
  "transaction_turnover": "Turnover",
  "selling_price": "Selling price",
  "selling_quantity": "Selling quantity",
  "can_sell": "Can sell",
  "please_enter_sell_price": "Please enter the selling price.",
  "please_enter_sell_amount": "Please enter the quantity sold.",
  "sell_amount_not_enough": "Insufficient sellable quantity",
  "current_delegation": "Current delegation",
  "historical_delegate": "Historical delegate",
  "receive_wallet_address": "Cashier's Wallet Address",
  "transfer_amount": "Transfer amount",
  "current_balance": "Current balance",
  "slow": "Slow",
  "fast": "Fast",
  "please_enter_receive_wallet_address": "Please enter the address of the payee's wallet.",
  "please_enter_transfer_amount": "Please enter the amount of transfer.",
  "from": "From",
  "to": "To",
  "account": "Account",
  "please_enter_transform_amount": "Please enter the transfer amount.",
  "all_transfer": "All in",
  "remark_choise": "Remarks (optional)",
  "roll_out": "Turn out",
  "shift_to": "Shift to",
  "pay_party": "Issuing party",
  "receive_party": "Receiving party",
  "block": "block",
  "no_copy_content": "No replicable content",
  "transform_record": "Transfer record",
  "transfer_to_wallet": "Transfer to Wallet",
  "transfer_to_currency_account": "Transfer to Currency Account",
  "wallet_backup_tips1": "Copy down your account mnemonic",
  "wallet_backup_tips2": "Backup Account: Export mnemonic and copy it to a safe place. Never save it on the network.",
  "wallet_backup_tips3": "Please confirm your account mnemonic",
  "wallet_backup_tips4": "Please click on mnemonics in order to ensure that your backup mnemonics are correct",
  "wallet_backup_tips5": "If someone acquires your mnemonic, they will directly acquire your assets! Please copy the mnemonics and store them in a safe place.",
  "next": "Next",
  "confirm_reset": "Are you sure about the reset?",
  "please_backup_words": "Please backup the complete mnemonic",
  "backup_account": "Backup account",
  "no_screenshots.": "No screenshots.",
  "got_it": "Got it",
  "change_password": "Change Password",
  "forget_or_import": "Forget the password? Import mnemonics or private keys to reset passwords",
  "delete_wallet": "Delete Wallet",
  "please_enter_receive_amount": "Please enter the amount of the receipt.",
  "plaintext_private_key": "Plaintext private key",
  "start_importing": "Start importing",
  "please_enter_key": "Please input Key",
  "import_keystore_tips": "Copy and paste the contents of the Keystore file in the official wallet of ETF into the input box or enter the two-dimensional code generated by scanning the Keystore content.",
  "keystore_text_content": "Keystore文本内容",
  "keystore_password": "Keystore password",
  "please_enter_keystore": "Please enter keystore",
  "mnemonic_word": "Mnemonic word",
  "private_key": "Private key",
  "word_only_in_lucky": "Mnemonic words are used only in lucky",
  "export": "Export",
  "price": "price",
  "Chg": "Chg",
  "message": "message",
  "logon_has_expired": "Logon has expired. Please log in again.",
  "connection": "connection",
  "network_is_error": "The network is running errors. Please try again later.",
  "drop_down_refresh": "Drop-down refresh",
  "release_and_refresh": "Release and refresh",
  "drop_down_loading": "Drop-down loading",
  "release_and_loading": "Loose loading",
  "loading": "loading",
  "copy_success": "Copy success",
  'copy_fail': "Replication failed, please try again",
  "just": "just",
  "minutes_ago": "minutes ago",
  "today": "today",
  "yesterday": "yesterday",
  "return_exit": "Press the return key again to exit",
  "Sunday": "Sunday",
  "Monday": "Monday",
  "Tuesday": "Tuesday",
  "Wednesday": "Wednesday",
  "Thursday": "Thursday",
  "Friday": "Friday",
  "Saturday": "Saturday",
  "before_dawn": "Before dawn",
  "morning": "morning",
  "afternoon": "afternoon",
  "night": "night",
  "noon": "noon",
  "before_yesterday": "The day before yesterday",
  "hintText": "Alignment bar code/two-dimensional code, automatic scanning",
  "albumText": "Album",
  "lightText": "Touch and light up",
  "closeText": "Touch close",
  "Number": "Number",
  "this_group": "This group",
  "copy_address": "Copy address",
  "share_friend":"Share friends",
  "push_setting": "Message push settings",
  "set_success": "Set up successfully",

  "withdraw_coin": "Withdraw money",
  "withdraw_coin_address": "Address",
  "withdraw_coin_amoiunt": "Amount",
  "please_enter_withdraw_coin_address": "Please enter the address of withdrawal",
  "please_enter_withdraw_coin_amount": "Please enter the quantity of withdrawal currency",
  "please_enter_remark": "Please enter comments",

  "apply_game_agent": "Apply for game promotion",
  "your_is_agent": "You are already the agent",
  "submit_apply": "Submit an application",





  "wechat_sign_in": "wechat sign in",
  "phone_register": "phone register",
  "tip_nickname": "Nickname is only used to show that user cannot log in",
  "forget_password": "forget password",
  "bind_phone": "bind phone",
  "safe": "safe",
  "notice": "notice",
  "complaint": "complaint",
  "bank_card": "bank card",
  "authentication_failed": "authentication failed",
  "my": "my",
  "Please_keep_the_verification_code_carefully": "Please keep the verification code carefully",
  "Please_confirm_payment_password": "Please confirm payment password",
  "reasons_for_reporting": "reasons for reporting",
  "Please_enter_the_content": "Please enter the content",
  "reply_time": "reply time",
  "ID_number": "ID number",
  "Please_enter_ID_number": "Please enter ID number",
  "Upload_ID_card_front_picture": "Upload ID card front picture",
  "Upload_ID_card_back_picture": "Upload ID card back picture",
  "Please_enter_your_name": "Please enter your name",
  "name": "name",
  "upload_audit": "upload audit",
  "system_message": "system message",
  "user_message": "user message",
  "recharge_message": "recharge message",
  "withdraw_message": "withdraw message",
  "push_notification_settings": "push notification settings",
  "set_up_successfully": "set up successfully",
  "logout_account": "logout account",
  "share": "share",
  "Are_you_sure_to_delete_this_session": "Are you sure to delete this session?",
  "game_redpacket": "game redpacket",
  "go_to_talk_with_your_friends": "go to talk with your friends~",
  "network_connection": "network_connection",
  "message_notification": "Notification",
  "group_chat": "Group Chat",
  "blacklist": "Blacklist",
  "initiate_group_chat": "New Chat",
  "tip_scan": "Please scan the QR code of personal or group chat on this platform",
  "remove_from_blacklist": "Remove from blacklist",
  "Are_you_sure_to_remove_from_the_blacklist": "Are you sure to remove from the blacklist?",
  "Do_you_want_to_open_an_external_link": "Do you want to open an external link?",
  "group_validity_period": "Group Validity Period",
  "tip_open_group": "Enable for Pemerna",
  "select_expiration_date": "Expiration date",
  "group_brief": "group brief",
  "members_add_friends_to_each_other": "members add friends",
  "total_ban": "total ban",
  "Only_the_group_leader_can_modify_the_Avatar": "Only the group leader can modify the Avatar",
  "add": "add",
  "search_mobile": "search mobile",
  "head": "head",
  "sex": "sex",
  "male": "male",
  "female": "female",
  "birthday": "birthday",
  "my_QR": "my QR",
  "set_sex": "set sex",
  "personal_settings": "personal settings",
  "Amount": "Amount",
  "yuan": "yuan",
  "ge": "",

  'mine_extract_coin': 'Withdraw money',
  'wallet_choose_coin': 'coin',
  'account_balance': 'account balance',
  'wallet_get_coin_num': 'number',
  'wallet_service_charge': 'charge',
  'wallet_coin_address': 'address',
  'network_error': 'The server is deserted. Please try again.',
  'msg_enter_coin_number': 'Please input the amount of money to withdraw.',
  'msg_enter_coin_address': 'Please input the currency address.',
  'regex_pay_password': 'Please enter 6 digit pure digital password',
  'msg_submit_success_audite': 'Successful submission',
  'home_receipt': 'receipt',
  'home_coin': 'coin',
  'wallet_receipt_address': 'addrss',
  'wallet_receipt_money': 'amount',
  'wallet_receipt_money_please': 'Please enter the amount.',
  'transfer': 'transfer',
  'wallet_receipt_address_please': 'Payee wallet address',
  'wallet_transfer_money': 'amount',
  'wallet_cur_balance': 'balance',
  'msg_receipt_wallet_address': "Please enter the payee's wallet address.",
  'msg_enter_transfer_money': 'Please input the transfer amount.',
  'confirm_enter_wallet_password': 'Please enter your wallet transaction password.',
  'please_enter_pay_password': 'Please enter the transaction password.',
  'order_number': 'order number',
  'coin_type': 'coin type',
  'coin_number': 'coin number',
  "wallet_record": 'wallet record',
  "withdraw": 'withdraw',
  "transfer": 'transfer',
  "copy_wallet_address": 'copy wallet address',
  "video": 'video',
  "upload_successfully": 'upload successfully',
  'group_received_a_video': 'A video was received in the group.',
  'you_send_a_video': 'You sent a video to each other.',
  'you_receive_a_video': 'You received a video.',
  "name_card": 'card',
  "single_card": 'card',
  "group_card": 'group card',
  "send_card": 'send card',
  'group_received_a_card': 'A card was received in the group.',
  'you_send_a_card': 'You sent a card to each other.',
  'you_receive_a_card': 'You received a card.',
  "file": 'file',
  "send_successfully": 'send successfully',
  "tip_file_limit": 'File size cannot exceed 25mb!',
  'group_received_a_file': 'A file was received in the group.',
  'you_send_a_file': 'You sent a file to each other.',
  'you_receive_a_file': 'You received a file.',
  "recharge_success": 'recharge success',
  "recharge_failed": 'recharge failed',
  "withdraw_success": 'withdraw success',
  "withdrawing": 'withdrawing',
  "withdraw_failed": 'withdraw failed',
  "address": 'address',
  "withdraw_record": 'withdraw record',
}

var kor = {

}

var jp = {

}
